name: push_to_io

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          token: ${{ secrets.key }}
        run: |
          git clone https://github.com/sturlabragason/sturlabragason.github.io.git
          cp README.md ./sturlabragason.github.io/sturla.txt
          sed -i '1d;$d' ./sturlabragason.github.io/sturla.txt
          sed -i '1 i\<pre style="color:lime;">' ./sturlabragason.github.io/sturla.txt
          sed -i -e '$a</pre>' ./sturlabragason.github.io/sturla.txt
          cd sturlabragason.github.io
          git config --global user.name "Sturla Bragason"
          git config --global user.email sturla.bragason@gmail.com
          git remote set-url origin https://sturlabragason:"$token"@github.com/sturlabragason/sturlabragason.github.io.git
          d=$(date +%Y-%m-%d)
          git add --all && git commit --all -m "$d" && git push